# -*- coding: utf-8 -*-
"""网络工程师(5)、数据库工程师(6)、高项(8) 的 multi/judge/fill 补充题库"""

EXTRA = {
    5: {
        "multi": {
            "medium": [
                ("VLAN 优点包括（  ）。", '["A. 隔离广播域", "B. 提高安全", "C. 灵活组网", "D. 提高物理带宽"]', "A,B,C", "VLAN 逻辑划分广播域，不直接增加物理带宽。"),
                ("NAT 类型包括（  ）。", '["A. 静态NAT", "B. 动态NAT", "C. PAT/NAPT", "D. 反向ARP"]', "A,B,C", "反向ARP 已淘汰，与 NAT 无关。"),
                ("OSPF 特点（  ）。", '["A. 链路状态", "B. 支持 VLSM", "C. 区域划分", "D. 跳数限制15"]', "A,B,C", "跳数15是 RIP 限制。"),
                ("TCP 拥塞控制包括（  ）。", '["A. 慢开始", "B. 拥塞避免", "C. 快重传", "D. 轮询"]', "A,B,C", "轮询不是 TCP 拥塞控制算法。"),
                ("无线 AP 功能（  ）。", '["A. 接入点", "B. 桥接", "C. 认证", "D. 路由必含"]', "A,B,C", "AP 可以不做路由。"),
                ("SNMP 组件（  ）。", '["A. Manager", "B. Agent", "C. MIB", "D. DNS"]', "A,B,C", "DNS 非 SNMP 组件。"),
                ("链路聚合优点（  ）。", '["A. 带宽叠加", "B. 冗余", "C. 负载分担", "D. 消除广播"]', "A,B,C", "链路聚合不消除广播。"),
                ("IPSec 协议（  ）。", '["A. AH", "B. ESP", "C. IKE", "D. FTP"]', "A,B,C", "FTP 是应用层。"),
                ("DHCP 过程消息（  ）。", '["A. Discover", "B. Offer", "C. Request", "D. ACK"]', "A,B,C,D", "DORA 四步。"),
                ("网络分层好处（  ）。", '["A. 降低复杂度", "B. 标准化接口", "C. 便于维护", "D. 消除延迟"]', "A,B,C", "分层不能消除延迟。"),
            ],
            "hard": [
                ("BGP 路径属性（  ）。", '["A. AS_PATH", "B. NEXT_HOP", "C. LOCAL_PREF", "D. VLAN ID"]', "A,B,C", "VLAN ID 是二层概念。"),
                ("MPLS 标签栈用于（  ）。", '["A. 快速转发", "B. VPN", "C. TE", "D. MAC 学习"]', "A,B,C", "MAC 学习是交换机行为。"),
                ("SDN 特征（  ）。", '["A. 控制与转发分离", "B. 可编程", "C. 集中控制", "D. 仅物理层"]', "A,B,C", "SDN 不限于物理层。"),
                ("IPv6 过渡技术（  ）。", '["A. 双栈", "B. 隧道", "C. NAT64", "D. RIP v1"]', "A,B,C", "RIPv1 与 IPv6 过渡无关。"),
                ("零信任原则（  ）。", '["A. 永不信任始终验证", "B. 最小权限", "C. 微分段", "D.  perimeter 足够"]', "A,B,C", "零信任否定仅靠边界防护。"),
                ("QoS 机制（  ）。", '["A. 分类标记", "B. 队列调度", "C. 流量整形", "D. 编译优化"]', "A,B,C", "编译优化无关 QoS。"),
                ("802.1Q 标签字段含（  ）。", '["A. TPID", "B. PCP", "C. VID", "D. TTL"]', "A,B,C", "TTL 在网络层。"),
                ("网络虚拟化包括（  ）。", '["A. VLAN", "B. VXLAN", "C. NFV", "D. 仅物理拓扑"]', "A,B,C", "虚拟化超越物理拓扑。"),
                ("DDoS 防护（  ）。", '["A. 流量清洗", "B. 限速", "C. 黑名单", "D. 明文存储密码"]', "A,B,C", "明文密码是安全隐患。"),
                ("IPv4 子网划分需考虑（  ）。", '["A. 主机数", "B. 子网数", "C. 掩码长度", "D. 编译器版本"]', "A,B,C", "编译器无关。"),
            ],
        },
        "judge": {
            "easy": [
                ("Hub 是物理层设备，所有端口同一冲突域。（  ）", None, "正确", "集线器 hub 物理层广播，共享冲突域。"),
                ("TCP 端口号 16 位。（  ）", None, "正确", "TCP/UDP 端口均为 16 位。"),
                ("127.0.0.1 可用于测试本机 TCP/IP 协议栈。（  ）", None, "正确", "回环地址用于本机测试。"),
                ("交换机学习 MAC 地址构建 MAC 地址表。（  ）", None, "正确", "二层交换机动态学习源 MAC。"),
                ("UDP 首部比 TCP 首部简单。（  ）", None, "正确", "UDP 8 字节固定首部，TCP 至少 20 字节。"),
                ("光纤不受电磁干扰影响。（  ）", None, "正确", "光纤传输光信号，抗 EMI。"),
                ("DNS 只能使用 UDP。（  ）", None, "错误", "DNS 大响应或区域传输用 TCP。"),
                ("默认网关是本网段出口路由器地址。（  ）", None, "正确", "主机通过默认网关访问外网。"),
                ("ICMP 在网络层。（  ）", None, "正确", "ICMP 封装在 IP 中，属网络层。"),
                ("无线网络必须使用 WEP 加密。（  ）", None, "错误", "应使用 WPA2/WPA3，WEP 已不安全。"),
            ],
            "medium": [
                ("RIP 使用跳数作为度量。（  ）", None, "正确", "RIP 以跳数 metric，最大 15。"),
                ("Trunk 端口可承载多个 VLAN 流量。（  ）", None, "正确", "802.1Q Trunk 打 tag 传多 VLAN。"),
                ("NAT 改变 IP 报文源或目的地址。（  ）", None, "正确", "NAT 修改 IP 地址/port 映射。"),
                ("OSPF 支持等价负载均衡。（  ）", None, "正确", "OSPF 可对等价路径 ECMP。"),
                ("ARP 将 IP 解析为 MAC。（  ）", None, "正确", "ARP Address Resolution Protocol。"),
                ("防火墙只能部署在网络边界。（  ）", None, "错误", "也可部署在主机、内部区域。"),
                ("IPv6 地址配置只能手动。（  ）", None, "错误", "支持 SLAAC 和 DHCPv6。"),
                ("STP 阻塞端口仍接收 BPDU。（  ）", None, "正确", "阻塞态接收 BPDU 监听拓扑变化。"),
                ("HTTPS 对 HTTP  body 加密。（  ）", None, "正确", "TLS 加密应用层数据。"),
                ("子网划分会减少可用主机地址。（  ）", None, "正确", "每个子网损失网络地址和广播地址。"),
            ],
            "hard": [
                ("BGP 选路仅看 AS_PATH 长度。（  ）", None, "错误", "BGP 有多属性决策流程，AS_PATH 只是其一。"),
                ("MPLS 标签在每一跳都会被替换或弹出。（  ）", None, "正确", "LSR 进行 swap/pop/push 标签操作。"),
                ("VXLAN 使用 24 位 VNI。（  ）", None, "正确", "VXLAN Network Identifier 24 位。"),
                ("IPSec AH 提供机密性。（  ）", None, "错误", "AH 提供认证和完整性，ESP 提供加密。"),
                ("Anycast 同一地址多个节点，路由到最近。（  ）", None, "正确", "任播 IPv6/BGP anycast 典型应用。"),
                ("802.1X 仅用于无线。（  ）", None, "错误", "有线和无线端口均可 802.1X。"),
                ("TCP Fast Open 减少握手延迟。（  ）", None, "正确", "TFO 在 SYN 携带数据减少 RTT。"),
                ("GRE 提供加密。（  ）", None, "错误", "GRE 仅封装，加密需配合 IPSec。"),
                ("链路状态协议易形成环路。（  ）", None, "错误", "链路状态通过 SPF 算无环最短路径。"),
                ("SD-WAN 只能使用 MPLS。（  ）", None, "错误", "SD-WAN 可基于 Internet/MPLS 等多种链路。"),
            ],
        },
        "fill": {
            "easy": [
                ("TCP 三次握手第二步服务器回复 ___ 。", None, "SYN+ACK", "第二次 SYN/ACK。"),
                ("MAC 地址共 ___ 字节。", None, "6", "48 位=6 字节。"),
                ("HTTP 明文默认端口 ___ 。", None, "80", "HTTPS 443。"),
                ("ICMP 中 Ping 使用 Echo ___ 报文。", None, "Request", "Echo Request/Reply。"),
                ("IPv4 地址 ___ 位。", None, "32", "IPv6 128 位。"),
                ("交换机根据 ___ 地址转发。", None, "MAC", "二层 MAC 转发。"),
                ("DNS 将域名解析为 ___ 。", None, "IP", "Domain Name System。"),
                ("子网掩码 255.255.255.0 写作 /___ 。", None, "24", "24 个网络位。"),
                ("无线标准 IEEE ___ 。", None, "802.11", "以太网 802.3。"),
                ("路由器工作在第 ___ 层。", None, "3", "网络层。"),
            ],
            "medium": [
                ("OSPF 骨干区域编号为 Area ___ 。", None, "0", "Area 0 backbone。"),
                ("NAT 多对一端口映射称 NAPT 或 ___ 。", None, "PAT", "Port Address Translation。"),
                ("VLAN 间路由称 ___ VLAN 路由。", None, "Inter", "Inter-VLAN routing。"),
                ("RIP 使用距离向量，最大跳数 ___ 。", None, "15", "16 不可达。"),
                ("TCP 确认号表示期望收到下一个字节的 ___ 。", None, "序号", "Sequence/Acknowledgment。"),
                ("STP 阻塞端口最终有一个变为 ___ 端口转发。", None, "指定/根", "根端口和指定端口转发。"),
                ("Trunk 封装标准 IEEE ___ 。", None, "802.1Q", "Dot1Q tag。"),
                ("SNMPv3 提供认证和 ___ 。", None, "加密", "SNMPv3 security。"),
                ("DHCP 租约到期客户端发送 ___ 续租。", None, "Request", "Renew/Rebind。"),
                ("ACL 扩展型可匹配源目 IP 和 ___ 。", None, "端口", "Extended ACL。"),
            ],
            "hard": [
                ("BGP 路径向量协议，运行于 TCP ___ 端口。", None, "179", "BGP peer 179。"),
                ("MPLS 标签 ___ 位。", None, "20", "Label 20+3+1+8+3 bit fields。"),
                ("VXLAN 封装在 ___ 层 UDP 中。", None, "传输", "UDP 4789 默认。"),
                ("IPSec 隧道模式封装整个原始 ___ 。", None, "IP包", "Transport 仅封装上层。"),
                ("802.1X 认证服务器常用 ___ 协议。", None, "RADIUS", "或 TACACS+。"),
                ("OSPF LSA 类型 1 称 Router ___ 。", None, "LSA", "Router LSA。"),
                ("Anycast 路由选择 ___ 路径。", None, "最近", "Shortest path to nearest。"),
                ("GRE 协议号 ___ 。", None, "47", "IP protocol 47。"),
                ("SDN 南向接口如 ___ 。", None, "OpenFlow", "OpenFlow 等。"),
                ("IPv6 链路本地地址前缀 FE80::/___ 。", None, "10", "Link-local。"),
            ],
        },
    },
    6: {
        "multi": {
            "easy": [
                ("SQL 语言包括（  ）。", '["A. DDL", "B. DML", "C. DCL", "D. HTML"]', "A,B,C", "HTML 非 SQL 子语言。"),
                ("完整性约束包括（  ）。", '["A. 实体", "B. 参照", "C. 用户定义", "D. 编译"]', "A,B,C", "实体/参照/域/用户定义完整性。"),
                ("关系运算包括（  ）。", '["A. 选择", "B. 投影", "C. 连接", "D. 编译"]', "A,B,C", "关系代数基本运算。"),
                ("索引优点（  ）。", '["A. 加速查询", "B. 唯一约束", "C. 加速排序", "D. 必减存储"]', "A,B,C", "索引占用额外存储。"),
                ("事务特性 ACID（  ）。", '["A. 原子", "B. 一致", "C. 隔离", "D. 持久"]', "A,B,C,D", "四特性。"),
                ("范式包括（  ）。", '["A. 1NF", "B. 2NF", "C. 3NF", "D. BCNF"]', "A,B,C,D", "常见范式。"),
                ("视图优点（  ）。", '["A. 简化查询", "B. 安全控制", "C. 逻辑独立", "D. 必提高写性能"]', "A,B,C", "视图可能降低写性能。"),
                ("DBMS 功能（  ）。", '["A. 定义", "B. 操纵", "C. 控制", "D. 编译 C"]', "A,B,C", "DBMS 不编译 C。"),
                ("SQL 聚合函数（  ）。", '["A. COUNT", "B. SUM", "C. AVG", "D. PRINT"]', "A,B,C", "PRINT 非标准聚合。"),
                ("外键作用（  ）。", '["A. 参照完整性", "B. 级联操作", "C. 关联表", "D. 加密"]', "A,B,C", "外键不用于加密。"),
            ],
            "medium": [
                ("并发问题包括（  ）。", '["A. 脏读", "B. 不可重复读", "C. 幻读", "D. 编译错"]', "A,B,C", "三大并发读问题。"),
                ("隔离级别（  ）。", '["A. 读未提交", "B. 读已提交", "C. 可重复读", "D. 串行化"]', "A,B,C,D", "SQL 标准四级。"),
                ("日志类型（  ）。", '["A. REDO", "B. UNDO", "C. 检查点", "D. 编译"]', "A,B,C", "恢复日志机制。"),
                ("BCNF 条件（  ）。", '["A. 3NF", "B. 决定因素是候选键", "C. 消除所有依赖", "D. 仅多值"]', "A,B", "BCNF 强化 3NF。"),
                ("数据仓库特点（  ）。", '["A. 面向主题", "B. 集成", "C. 相对稳定", "D. 高频更新 OLTP"]', "A,B,C", "DW 低频批量加载。"),
                ("NoSQL 类型（  ）。", '["A. 键值", "B. 文档", "C. 列族", "D. 关系"]', "A,B,C", "关系型非 NoSQL。"),
                ("备份类型（  ）。", '["A. 完全", "B. 增量", "C. 差异", "D. 编译"]', "A,B,C", "备份策略类型。"),
                ("查询优化（  ）。", '["A. 索引", "B. 重写", "C. 统计信息", "D. 删除表"]', "A,B,C", "删除表非优化手段。"),
                ("触发器时机（  ）。", '["A. BEFORE", "B. AFTER", "C. INSTEAD OF", "D. NEVER"]', "A,B,C", "常见触发时机。"),
                ("分布式事务（  ）。", '["A. 2PC", "B. 3PC", "C. Saga", "D. 单库本地"]', "A,B,C", "单库非分布式。"),
            ],
            "hard": [
                ("4NF 要求（  ）。", '["A. BCNF", "B. 消除非平凡MVD", "C. MVD determinant超键", "D. 仅函数依赖"]', "A,B,C", "4NF 处理多值依赖。"),
                ("MVCC 实现（  ）。", '["A. 版本链", "B. 快照读", "C. 无锁读", "D. 无事务"]', "A,B,C", "MVCC 仍支持事务。"),
                ("OLAP 操作（  ）。", '["A. 上卷", "B. 下钻", "C. 切片", "D. 编译"]', "A,B,C", "多维分析操作。"),
                ("CAP（  ）。", '["A. 一致性", "B. 可用性", "C. 分区容忍", "D. 编译"]', "A,B,C", "CAP 定理。"),
                ("Armstrong 公理（  ）。", '["A. 自反", "B. 增广", "C. 传递", "D. 分解"]', "A,B,C", "分解是导出规则非公理。"),
                ("索引结构（  ）。", '["A. B+树", "B. 哈希", "C. 位图", "D. 栈"]', "A,B,C", "栈非索引结构。"),
                ("数据挖掘任务（  ）。", '["A. 分类", "B. 聚类", "C. 关联", "D. 编译"]', "A,B,C", "数据挖掘典型任务。"),
                ("两阶段锁（  ）。", '["A. 增长阶段", "B. 收缩阶段", "C. 可串行化", "D. 无锁"]', "A,B,C", "2PL 协议阶段。"),
                ("反规范化手段（  ）。", '["A. 冗余列", "B. 派生列", "C. 预聚合", "D. 消除键"]', "A,B,C", "不能消除键。"),
                ("快照隔离（  ）。", '["A. 一致性读", "B. 可能写偏斜", "C. 无脏读", "D. 完全等同串行化"]', "A,B,C", "SI 弱于串行化。"),
            ],
        },
        "judge": {
            "easy": [
                ("SELECT 属于 DML。（  ）", None, "正确", "SELECT/INSERT/UPDATE/DELETE 均为 DML。"),
                ("主键值不能为 NULL。（  ）", None, "正确", "主键实体完整性要求非空唯一。"),
                ("外键值必须为 NULL 或引用存在的主键。（  ）", None, "正确", "参照完整性约束。"),
                ("视图可以基于多个表定义。（  ）", None, "正确", "视图是多表 JOIN 的虚表。"),
                ("索引越多 INSERT 一定越快。（  ）", None, "错误", "索引增加维护开销，降低写性能。"),
                ("1NF 消除重复组。（  ）", None, "正确", "第一范式要求属性原子、无重复组。"),
                ("ROLLBACK 撤销未提交事务。（  ）", None, "正确", "TCL 事务控制。"),
                ("关系是二维表的数学表示。（  ）", None, "正确", "关系模型基础。"),
                ("DBMS 位于用户与 OS 之间。（  ）", None, "正确", "数据库管理系统层次。"),
                ("HAVING 可单独无 GROUP BY 使用(标准SQL一般不行)。（  ）", None, "错误", "HAVING 通常配合 GROUP BY。"),
            ],
            "medium": [
                ("2NF 消除部分函数依赖。（  ）", None, "正确", "第二范式定义。"),
                ("BCNF 一定满足 3NF。（  ）", None, "正确", "BCNF 比 3NF 更严。"),
                ("脏读发生在读未提交级别。（  ）", None, "正确", "Read Uncommitted 可能脏读。"),
                ("B+ 树所有关键字也在叶子出现。（  ）", None, "正确", "B+ 树内部结点仅索引，叶子含数据。"),
                ("级联更新会同步更新从表外键。（  ）", None, "正确", "ON UPDATE CASCADE。"),
                ("星型模式中心是事实表。（  ）", None, "正确", "维度表围绕事实表。"),
                ("哈希索引支持范围查询。（  ）", None, "错误", "哈希仅等值。"),
                ("REDO 日志用于崩溃恢复已提交事务。（  ）", None, "正确", "前向恢复。"),
                ("UNION 自动去重。（  ）", None, "正确", "UNION ALL 不去重。"),
                ("触发器由事件自动执行。（  ）", None, "正确", "触发器响应 DML/DDL 事件。"),
            ],
            "hard": [
                ("4NF 强于 BCNF。（  ）", None, "正确", "处理多值依赖更严格。"),
                ("2PC 协调者故障一定导致数据不一致。（  ）", None, "错误", "可能导致阻塞，但日志可保证一致。"),
                ("MVCC 读写不阻塞(快照读)。（  ）", None, "正确", "InnoDB 快照读无锁。"),
                ("反规范化总是错误的设计。（  ）", None, "错误", "DW/报表场景常反规范化换性能。"),
                ("可串行化隔离级别无幻读。（  ）", None, "正确", "最高隔离级别。"),
                ("OLTP 和 OLAP 负载特征相同。（  ）", None, "错误", "OLTP 短事务高并发，OLAP 复杂查询。"),
                ("分布式数据库一定满足强一致。（  ）", None, "错误", "CAP 限制，可最终一致。"),
                ("函数依赖满足传递律。（  ）", None, "正确", "Armstrong 传递律。"),
                ("ETL 中 Extract 是抽取。（  ）", None, "正确", "Extract-Transform-Load。"),
                ("快照隔离等价于可重复读(各实现不同)。（  ）", None, "错误", "SI 与 RR 语义有差异。"),
            ],
        },
        "fill": {
            "easy": [
                ("SQL 插入语句关键字 ___ 。", None, "INSERT", "INSERT INTO ... VALUES。"),
                ("主键约束关键字 PRIMARY ___ 。", None, "KEY", "PRIMARY KEY。"),
                ("删除表结构语句 ___ TABLE 。", None, "DROP", "DROP TABLE。"),
                ("关系代数投影符号 ___ 。", None, "π", "pi 投影。"),
                ("事务提交命令 ___ 。", None, "COMMIT", "或 BEGIN/COMMIT/ROLLBACK。"),
                ("消除重复行关键字 ___ 。", None, "DISTINCT", "SELECT DISTINCT。"),
                ("1NF 要求属性 ___ 。", None, "原子", "atomic。"),
                ("DBA 中文名数据库 ___ 管理员。", None, "系统", "Database Administrator。"),
                ("外键引用 ___ 完整性。", None, "参照", "Referential integrity。"),
                ("查询语言标准 ___ 。", None, "SQL", "Structured Query Language。"),
            ],
            "medium": [
                ("2NF 消除 ___ 函数依赖。", None, "部分", "Partial FD。"),
                ("3NF 消除 ___ 依赖。", None, "传递", "Transitive FD。"),
                ("读已提交隔离级别英文 Read ___ 。", None, "Committed", "Isolation level。"),
                ("REDO 日志用于 ___ 操作。", None, "重做", "Redo committed work。"),
                ("UNDO 日志用于 ___ 操作。", None, "撤销", "Undo uncommitted。"),
                ("星型模式维度表围绕 ___ 表。", None, "事实", "Fact table。"),
                ("哈希索引适合 ___ 查询。", None, "等值", "Equality only。"),
                ("BCNF 中每个决定因素是 ___ 。", None, "候选键", "Candidate key。"),
                ("级联删除 ON DELETE ___ 。", None, "CASCADE", "Referential action。"),
                ("数据仓库 ETL 中 E 是 ___ 。", None, "抽取", "Extract。"),
            ],
            "hard": [
                ("4NF 消除非平凡 ___ 依赖。", None, "多值", "Multivalued dependency。"),
                ("2PC 第一阶段发送 ___ 。", None, "prepare", "Prepare to commit。"),
                ("MVCC 全称多版本 ___ 控制。", None, "并发", "Multi-Version Concurrency Control。"),
                ("Armstrong 公理：自反、增广、___ 。", None, "传递", "Transitivity。"),
                ("OLAP 上卷英文 ___ 。", None, "Roll-up", "Drill-down 下钻。"),
                ("CAP 中 P 是分区 ___ 。", None, "容忍", "Partition tolerance。"),
                ("可串行化英文 ___ 。", None, "Serializable", "Highest isolation。"),
                ("反规范化引入 ___ 换性能。", None, "冗余", "Denormalization。"),
                ("快照隔离缩写 ___ 。", None, "SI", "Snapshot Isolation。"),
                ("B+ 树叶子结点形成 ___ 。", None, "链表", "Linked leaves for range scan。"),
            ],
        },
    },
    8: {
        "multi": {
            "easy": [
                ("项目约束包括（  ）。", '["A. 范围", "B. 进度", "C. 成本", "D. 编译"]', "A,B,C", "铁三角约束。"),
                ("项目生命周期阶段（  ）。", '["A. 启动", "B. 规划", "C. 执行", "D. 收尾"]', "A,B,C,D", "加监控贯穿。"),
                ("干系人包括（  ）。", '["A. 客户", "B. 团队", "C. 供应商", "D. 仅 PM"]', "A,B,C", "干系人广泛。"),
                ("风险应对策略（  ）。", '["A. 规避", "B. 转移", "C. 减轻", "D. 接受"]', "A,B,C,D", "四种威胁应对。"),
                ("WBS 特点（  ）。", '["A. 可交付成果导向", "B. 100%规则", "C. 层次分解", "D. 越细越好"]', "A,B,C", "WBS 非越细越好。"),
                ("项目章程内容（  ）。", '["A. 目标", "B. 授权PM", "C. 高层需求", "D. 详细WBS"]', "A,B,C", "详细 WBS 在规划阶段。"),
                ("质量保证工具（  ）。", '["A. 质量审计", "B. 过程分析", "C. 因果图", "D. 仅测试"]', "A,B,C", "QA 不仅测试。"),
                ("沟通方式（  ）。", '["A. 正式", "B. 非正式", "C. 推式", "D. 拉式"]', "A,B,C,D", "多种沟通方式。"),
                ("变更控制步骤（  ）。", '["A. 申请", "B. 评估", "C. 审批", "D. 实施"]', "A,B,C,D", "整体变更控制。"),
                ("项目成功因素（  ）。", '["A. 清晰目标", "B. 干系人支持", "C. 有效沟通", "D. 无计划"]', "A,B,C", "需要计划。"),
            ],
            "medium": [
                ("关键路径特点（  ）。", '["A. 最长路径", "B. 总时差0", "C. 决定工期", "D. 唯一"]', "A,B,C", "关键路径可能多条。"),
                ("挣值指标（  ）。", '["A. CPI", "B. SPI", "C. EAC", "D. HTML"]', "A,B,C", "EVM 指标。"),
                ("估算技术（  ）。", '["A. 类比", "B. 参数", "C. 三点", "D. 编译"]', "A,B,C", "估算方法。"),
                ("合同类型（  ）。", '["A. 固定总价", "B. 成本补偿", "C. 工料", "D. 仅口头"]', "A,B,C", "正式合同类型。"),
                ("团队发展阶段（  ）。", '["A. 形成", "B. 震荡", "C. 规范", "D. 成熟"]', "A,B,C,D", "Tuckman 模型五阶段含解散。"),
                ("质量成本（  ）。", '["A. 预防", "B. 评价", "C. 内部失败", "D. 外部失败"]', "A,B,C,D", "COQ 四类。"),
                ("风险分类（  ）。", '["A. 威胁", "B. 机会", "C. 已知", "D. 未知"]', "A,B,C,D", "风险类型。"),
                ("配置管理（  ）。", '["A. 识别", "B. 控制", "C. 审计", "D. 仅编码"]', "A,B,C", "配置管理活动。"),
                ("采购过程（  ）。", '["A. 规划", "B. 实施", "C. 控制", "D. 关闭"]', "A,B,C,D", "采购四过程。"),
                ("敏捷实践（  ）。", '["A. 迭代", "B. 回顾", "C. 用户故事", "D. 无文档"]', "A,B,C", "敏捷重轻文档非无文档。"),
            ],
            "hard": [
                ("项目组合管理（  ）。", '["A. 战略对齐", "B. 资源优化", "C. 价值最大化", "D. 仅单项目"]', "A,B,C", "组合层管理多项目/项目集。"),
                ("EVM 预测（  ）。", '["A. EAC", "B. ETC", "C. TCPI", "D. WBS"]', "A,B,C", "完工预测指标。"),
                ("定量风险（  ）。", '["A. 蒙特卡洛", "B. 决策树", "C. EMV", "D. 仅头脑风暴"]', "A,B,C", "头脑风暴是定性工具。"),
                ("CCB 职责（  ）。", '["A. 评审变更", "B. 批准/拒绝", "C. 维护基线", "D. 写代码"]', "A,B,C", "CCB 不直接写代码。"),
                ("项目集（  ）。", '["A. 相关项目", "B. 统一治理", "C. 战略收益", "D. 无依赖"]', "A,B,C", "项目集项目有关联。"),
                ("配置基线（  ）。", '["A. 功能基线", "B. 分配基线", "C. 产品基线", "D. 仅预算"]', "A,B,C", "三类基线。"),
                ("激励理论（  ）。", '["A. 马斯洛", "B. 赫兹伯格", "C. 麦克利兰", "D. 编译"]', "A,B,C", "激励理论。"),
                ("国际项目管理（  ）。", '["A. 文化差异", "B. 虚拟团队", "C. 多时区", "D. 无沟通"]', "A,B,C", "需加强沟通。"),
                ("敏捷 scaling（  ）。", '["A. SAFe", "B. LeSS", "C. Nexus", "D. 仅个人"]', "A,B,C", "规模化敏捷框架。"),
                ("项目收尾（  ）。", '["A. 验收", "B. 移交", "C. 总结", "D. 仅解散"]', "A,B,C", "正式收尾活动。"),
            ],
        },
        "judge": {
            "easy": [
                ("项目是为创造独特产品、服务或成果的临时性工作。（  ）", None, "正确", "PMBOK 项目定义。"),
                ("项目经理对项目成败负最终责任。（  ）", None, "正确", "PM 整体责任。"),
                ("WBS 最底层是工作包。（  ）", None, "正确", "Work Package。"),
                ("项目范围说明书描述项目边界。（  ）", None, "正确", "范围基准组成部分。"),
                ("风险只包括威胁不包括机会。（  ）", None, "错误", "风险含威胁和机会。"),
                ("干系人可能支持或反对项目。（  ）", None, "正确", "干系人利益不同。"),
                ("项目必须具有明确的目标。（  ）", None, "正确", "项目有独特目标和约束。"),
                ("质量保证属于监控过程组。（  ）", None, "错误", "管理质量在执行过程组( PMBOK6 )；PMBOK7 有调整。"),
                ("变更请求需经过整体变更控制。（  ）", None, "正确", "Integrated Change Control。"),
                ("项目收尾包括释放资源。（  ）", None, "正确", "行政收尾活动。"),
            ],
            "medium": [
                ("关键路径延迟必导致项目延期。（  ）", None, "正确", "关键路径决定最短工期。"),
                ("CPI>1 表示成本节约。（  ）", None, "正确", "CPI=EV/AC。"),
                ("资源平衡可能改变关键路径。（  ）", None, "正确", "Resource leveling 可能延长工期。"),
                ("固定总价合同卖方成本风险大。（  ）", None, "正确", "FP 卖方承担成本超支风险。"),
                ("RACI 中 R 负责执行任务。（  ）", None, "正确", "Responsible vs Accountable。"),
                ("蒙特卡洛属于定量风险分析。（  ）", None, "正确", "模拟分析。"),
                ("项目集管理多个相关项目。（  ）", None, "正确", "Program management。"),
                ("质量审计是 QA 工具。（  ）", None, "正确", "过程审计。"),
                ("沟通管理计划规划沟通。（  ）", None, "正确", "规划过程输出。"),
                ("敏捷拒绝所有计划。（  ）", None, "错误", "敏捷适应变化但仍需规划。"),
            ],
            "hard": [
                ("TCPI>1 表示需提高剩余工作效率才能按预算完工。（  ）", None, "正确", "To-Complete Performance Index。"),
                ("PERT 使用贝塔分布三点估算。（  ）", None, "正确", "期望=(O+4M+P)/6。"),
                ("项目组合确保与组织战略一致。（  ）", None, "正确", "Portfolio alignment。"),
                ("配置审计分功能审计和物理审计。（  ）", None, "正确", "Configuration audit types。"),
                ("项目生命周期成本主要在维护阶段。（  ）", None, "正确", "全生命周期视角。"),
                ("敏感性分析一次只变一个因素。（  ）", None, "正确", "Sensitivity analysis。"),
                ("引导式研讨会可快速收集需求。（  ）", None, "正确", "Facilitated workshops/JAD。"),
                ("项目成功标准应可测量。（  ）", None, "正确", "SMART criteria。"),
                ("SPI<1 进度滞后。（  ）", None, "正确", "SPI=EV/PV。"),
                ("EVM 适用于任何规模项目无需 WBS。（  ）", None, "错误", "EVM 需要 WBS 和进度计划基础。"),
            ],
        },
        "fill": {
            "easy": [
                ("项目管理五大过程组：启动、规划、执行、监控、___ 。", None, "收尾", "Closing。"),
                ("WBS 英文 Work Breakdown ___ 。", None, "Structure", "工作分解结构。"),
                ("项目铁三角：范围、时间、___ 。", None, "成本", "Cost。"),
                ("风险登记册记录已识别 ___ 。", None, "风险", "Risk register。"),
                ("CCB 中文变更 ___ 委员会。", None, "控制", "Change Control Board。"),
                ("项目章程授权 ___ 经理。", None, "项目", "Project Manager。"),
                ("里程碑工期为 ___ 。", None, "0", "Zero duration。"),
                ("QA 关注 ___ 。", None, "过程", "Quality Assurance。"),
                ("QC 关注 ___ 。", None, "产品", "Quality Control。"),
                ("干系人 ___ 分析识别干系人。", None, "登记", "Stakeholder register。"),
            ],
            "medium": [
                ("关键路径总时差为 ___ 。", None, "0", "Total float=0。"),
                ("CPI 公式 EV 除以 ___ 。", None, "AC", "Cost Performance Index。"),
                ("SPI 公式 EV 除以 ___ 。", None, "PV", "Schedule Performance Index。"),
                ("类比估算又称 ___ 估算。", None, "自上而下", "Top-down。"),
                ("FP 合同中文固定 ___ 合同。", None, "总价", "Fixed Price。"),
                ("RACI 中 C 表示 ___ 。", None, "咨询", "Consulted。"),
                ("蒙特卡洛 ___ 分析。", None, "模拟", "Simulation。"),
                ("质量成本 COQ 分一致性和非 ___ 成本。", None, "一致性", "Conformance vs non-conformance。"),
                ("采购合同工料合同英文 T&M Time and ___ 。", None, "Material", "Time and Material。"),
                ("敏捷迭代称 ___ 。", None, "Sprint", "Scrum Sprint。"),
            ],
            "hard": [
                ("PERT 期望公式 (O+4M+___)/6 。", None, "P", "Optimistic Most Pessimistic。"),
                ("TCPI 中文完工尚需 ___ 。", None, "绩效指数", "To-Complete Performance Index。"),
                ("EMV 期望 ___ 价值。", None, "货币", "Expected Monetary Value。"),
                ("配置管理 CM 基线经正式 ___ 。", None, "批准", "Approved baseline。"),
                ("项目集 Program 实现 ___ 收益。", None, "战略", "Strategic benefits。"),
                ("敏感性分析属于 ___ 风险分析。", None, "定量", "Quantitative。"),
                ("引导式研讨会 JAD 用于需求 ___ 。", None, "收集", "Requirements gathering。"),
                ("EVM 完工估算 EAC Estimate at ___ 。", None, "Completion", "EAC forecasting。"),
                ("SAFe 规模化 ___ 框架。", None, "敏捷", "Scaled Agile Framework。"),
                ("项目组合 Portfolio 对齐组织 ___ 。", None, "战略", "Strategy alignment。"),
            ],
        },
    },
}
